package de.tappd.Tappd.model.style;

public enum BeerStyles {
	// @formatter:off
	ALTBIERE("Altbier"),
	AMERICAN_WILD_ALE("American Wild Ale"),
	APPLEWINE("Applewine"),
	AUSTRALIAN_SPARKLING_ALE("Australian Sparkling Ale"),
	BARLEYWINE_AMERICAN("Barleywine - American"),
	BARLEYWINE_ENGLISH("Barleywine - English"),
	BARLEYWINE_OTHER("Barleywine - Other"),
	BELGIAN_BLOND("Belgian Blond(e)"),
	BELGIAN_DUBBEL("Belgian Dubbel"),
	BELGIAN_QUAD("Belgian Quad"),
	BELGIAN_STRONG_DARK_ALE("Belgian Strong Dark Ale"),
	BELGIAN_STRONG_GOLDEN_ALE("Belgian Strong Golden Ale"),
	BELGIAN_TRIPEL("Belgian Tripel"),
	BIERE_DE_CHAMPAGNE_BIERE_BRUT("Biere de Champagne / Biere Brut"),
	BIERE_DE_GARDE("Biere de Garde"),
	BLACK_TAN("Black Tan"),
	BLONDE_ALE("Blonde Ale"),
	BLONDE_ALE_BELGIAN_BLONDE_GOLDEN("Blonde Ale - Belgian Blonde / Golden"),
	BOCK("Bock"),
	BROWN_ALE_AMERICAN("Brown Ale - American"),
	BROWN_ALE_BELGIAN("Brown Ale - Belgian"),
	BROWN_ALE_ENGLISH("Brown Ale - English"),
	BROWN_ALE_IMPERIAL_DOUBLE("Brown Ale - Imperial / Double"),
	BROWN_ALE_OTHER("Brown Ale - Other"),
	BURTON_ALE("Burton Ale"),
	CALIFORNIA_COMMON("California Common"),
	CIDER("Cider"),
	CREAM_ALE("Cream Ale"),
	DAMPFBIER("Dampfbier"),
	DARK_ALE("Dark Ale"),
	DOPPELBOCK("Doppelbock"),
	DUNKELWEIZEN("Dunkelweizen"),
	EISBOCK("Eisbock"),
	ENGLISH_BITTER("English Bitter"),
	ENGLISH_MILD_ALE("English Mild Ale"),
	EXTRA_SPECIAL_STRONG_BITTER("Extra Special / Strong Bitter"),
	FESTBIER("Festbier"),
	FRUIT_BEER("Fruit Beery"),
	GINGER_BEER("Ginger Beer"),
	GLUTEN_FREE("Gluten-Free"),
	GOLDEN_ALE("Golden Ale"),
	GRISETTE("Grisette"),
	GRUIT_ANCIENT_HERBED_ALE("Gruit / Ancient Herbed Ale"),
	GRAETZER_GRODZISKIE("Graetzer / Grodziskie"),
	HAPPOSHU("Happoshu"),
	HEFEWEIZEN("Hefeweizen"),
	HEFEWEIZEN_LIGHT("Hefeweizen Light / Leicht"),
	HONEY_BEER("Honey Beer"),
	IPA_AMERICAN("IPA - American"),
	IPA_BELGIAN("IPA - Belgian"),
	IPA_BLACK_CASCADIAN_DARK_ALE("IPA - Black / Cascadian Dark Ale"),
	IPA_ENGLISH("IPA - English"),
	IPA_IMPERIAL_DOUBLE("IPA - Imperial / Double"),
	IPA_IMPERIAL_DOUBLE_BLACK("IPA - Imperial / Double Black"),
	IPA_INTERNATIONAL("IPA - International"),
	IPA_NEW_ENGLAND("IPA - New England"),
	IPA_RED("IPA - Red"),
	IPA_SESSION_INDIA_SESSION_ALE("IPA - Session / India Session Ale"),
	IPA_TRIPLE("IPA - Triple"),
	IPA_WHITE("IPA - White"),
	KELLERBIER_ZWICKELBIER("Kellerbier / Zwickelbier"),
	KOMBUCHA("Kombucha"),
	KRISTALLWEIZEN("Kristallweizen"),
	KVASS("Kvass"),
	KOELSCH("Koelsch"),
	LAGER_AMBER("Lager - Amber"),
	LAGER_AMERICAN_AMBER_RED("Lager - American Amber / Red"),
	LAGER_AMERICAN_LIGHT("Lager - American Light"),
	LAGER_DARK("Lager - Dark"),
	LAGER_DORTMUNDER_EXPORT("Lager - Dortmunder / Export"),
	LAGER_DUNKEL_MUNICH("Lager - Dunkel Munich"),
	LAGER_EURO("Lager - Euro"),
	LAGER_EURO_DARK("Lager - Euro Dark"),
	LAGER_EURO_STRONG("Lager - Euro Strong"),
	LAGER_HELLES("Lager - Helles"),
	LAGER_IPL_INDIA_PALE_LAGER("Lager - IPL (India Pale Lager)"),
	LAGER_JAPANESE_RICE("Lager - Japanese Rice"),
	LAGER_NORTH_AMERICAN_ADJUNCT("Lager - North American Adjunct"),
	LAGER_PALE("Lager - Pale"),
	LAGER_RED("Lager - Red"),
	LAGER_VIENNA("Lager - Vienna"),
	LAGER_WINTER("Lager - Winter"),
	LAMBI_FARO("Lambic - Faro"),
	LAMBI_FRAMBOISE("Lambic - Framboise"),
	LAMBI_FRUIT("Lambic - Fruit"),
	LAMBI_GUEUZE("Lambic - Gueuze"),
	LAMBI_KRIEK("Lambic - Kriek"),
	LAMBI_TRADITIONAL("Lambic - Traditional"),
	MAIBOCK_HELLER_BOCK("Maibock / Heller (Helles) Bock"),
	MALT_BEER("Malt Beer"),
	MALT_LIQUOR("Malt Liquor"),
	MEAD_BRAGGOT("Mead - Braggot"),
	MEAD_CYSER("Mead - Cyser"),
	MEAD_MELOMEL("Mead - Melomel"),
	MEAD_METHEGLIN("Mead - Metheglin"),
	MEAD_OTHER("Mead - Other"),
	MEAD_PYMENT("Mead - Pyment"),
	MUMME("Mumme"),
	MAERZEN("Maerzen"),
	NON_ALCOHOLIC("Non-Alcoholic"),
	OLD_ALE("Old Ale"),
	OTHER("Other"),
	PALE_ALE_AMERICAN("Pale Ale - American"),
	PALE_ALE_AUSTRALIAN("Pale Ale - Australian"),
	PALE_ALE_BELGIAN("Pale Ale - Belgian"),
	PALE_ALE_ENGLISH("Pale Ale - English"),
	PALE_ALE_INTERNATIONAL("Pale Ale - International"),
	PALE_ALE_NEW_ZEALAND("Pale Ale - New Zealand"),
	PALE_WHEAT_ALE_AMERICAN("Pale Wheat Ale - American"),
	PATERSBIER("Patersbier"),
	PERRY("Perry"),
	PILSNER_CZECH("Pilsner - Czech"),
	PILSNER_GERMAN("Pilsner - German"),
	PILSNER_IMPERIAL_DOUBLE("Pilsner - Imperial / Double"),
	PILSNER_OTHER("Pilsner - Other"),
	PORTER_AMERICAN("Porter - American"),
	PORTER_BALTIC("Porter - Baltic"),
	PORTER_ENGLISH("Porter - English"),
	PORTER_IMPERIAL_DOUBLE("Porter - Imperial / Double"),
	PORTER_OTHER("Porter - Other"),
	PUMPKIN_YAM_BEER("Pumpkin / Yam Beer"),
	PUMPKIN_YAM_BEER_IMPERIAL("Pumpkin / Yam Beer - Imperial"),
	RAUCHBIER("Rauchbier"),
	RED_ALE_AMERICAN_AMBER_RED("Red Ale - American Amber / Red"),
	RED_ALE_IMPERIAL_DOUBLE("Red Ale - Imperial / Double"),
	RED_ALE_IRISH("Red Ale - Irish"),
	RED_ALE_OTHER("Red Ale - Other"),
	ROGGENBIER("Roggenbier"),
	ROOT_BEER("Root Beer"),
	RYE_BEER("Rye Beer"),
	RYE_IPA("Rye IPA"),
	SAHTI("Sahti"),
	SAISON_FARMHOUSE_ALE("Saison / Farmhouse Ale"),
	SCHWARZBIER("Schwarzbier"),
	SCOTCH_ALE_WEE_HEAVY("Scotch Ale / Wee Heavy"),
	SCOTTISH_ALE("Scottish Ale"),
	SCOTTISH_EXPORT_ALE("Scottish Export Ale"),
	SHANDY_RADLER("Shandy / Radler"),
	SMOKED_BEER("Smoked Beer"),
	SOUR_ALE("Sour - Ale"),
	SOUR_BERLINER_WEISSE("Sour - Berliner Weisse"),
	SOUR_FARMHOUSE_IPA("Sour - Farmhouse IPA"),
	SOUR_FLANDERS_OUD_BRUIN("Sour - Flanders Oud Bruin"),
	SOUR_FLANDERS_RED_ALE("Sour - Flanders Red Ale"),
	SOUR_GOSE("Sour - Gose"),
	SPECIALTY_GRAIN("Specialty Grain"),
	SPICED_HERBED_BEER("Spiced / Herbed Beer"),
	STOUT_AMERICAN("Stout - American"),
	STOUT_AMERICAN_IMPERIAL_DOUBLE("Stout - American Imperial / Double"),
	STOUT_FOREIGN_EXPORT("Stout - Foreign / Export"),
	STOUT_IMPERIAL_DOUBLE("Stout - Imperial / Double"),
	STOUT_IMPERIAL_MILK_SWEET("Stout - Imperial Milk / Sweet"),
	STOUT_IMPERIAL_OATMEAL("Stout - Imperial Oatmeal"),
	STOUT_IRISH_DRY("Stout - Irish Dry"),
	STOUT_MILK_SWEET("Stout - Milk / Sweet"),
	STOUT_OATMEAL("Stout - Oatmeal"),
	STOUT_OTHER("Stout - Other"),
	STOUT_OYSTER("Stout - Oyster"),
	STOUT_RUSSIAN_IMPERIAL("Stout - Russian Imperial"),
	STRONG_ALE_AMERICAN("Strong Ale - American"),
	STRONG_ALE_ENGLISH("Strong Ale - English"),
	TABLE_BEER("Table Beer"),
	TRADITIONAL_ALE("Traditional Ale"),
	WEIZENBOCK("Weizenbock"),
	WHEAT_WINE("Wheat Wine"),
	WINTER_ALE("Winter Ale"),
	WINTER_WARMER("Winter Warmer"),
	WITBIER("Witbier"),
	ZOIGL("Zoigl");
	// @formatter:on

	private String displayName;

	private BeerStyles(String displayName) {
		this.displayName = displayName;
	}

	public String displayName() {
		return displayName;
	}
	
	@Override
	public String toString() {
		return displayName;
	}

}